ТипФайла: "Сценарий"
ДанныеСценария:
    UID: "863402ba-3fd2-11ed-be85-000c29b8212d"
    Имя: "Создание номенклатуры"
    Код: "000000022"
    Проект: "БИТ:УМЦ"
    ПроектUID: "82a1df0f-598a-4887-b4a5-bc1f2fd0e030"
    ФункцияСистемы: "Основной функционал"
    РазрешеноИспользоватьВДругихФункциях: "Нет"
    UIDФункцияСистемы: "fef4d3b0-38de-11ed-be78-000c29b8212d"
    UIDРазделПроекта: "2552c356-409f-11ed-be85-000c29b8212d"
    UIDОтветственный: "e7203090-38db-11ed-be78-000c29b8212d"
    Публикуется: "Нет"
    ПрофильПользователя: ""
    УровеньОтчета1: "Справочник Номенклатура"
    УровеньОтчета2: "Справочник Номенклатура"
    ОписаниеСценария: ""

ПараметрыСценария:
    - ПараметрыСценария1:
        НомерСтроки: "1"
        Имя: "НазваниеНоменклатуры"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария2:
        НомерСтроки: "2"
        Имя: "ВидНоменклатуры"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария3:
        НомерСтроки: "3"
        Имя: "НазваниеСпециализации"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария4:
        НомерСтроки: "4"
        Имя: "ПродолжительностьМинут"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария5:
        НомерСтроки: "5"
        Имя: "ЕдиницаИзмерения"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"


ТегиСценария:

ВложенныеСценарии:

ВызывающиеСценарии:

