ТипФайла: "Сценарий"
ДанныеСценария:
    UID: "e8ae1d44-3b28-11ed-be7f-000c29b8212d"
    Имя: "Создание документа \"Заявка\""
    Код: "000000004"
    Проект: "БИТ:УМЦ"
    ПроектUID: "82a1df0f-598a-4887-b4a5-bc1f2fd0e030"
    ФункцияСистемы: "Основной функционал"
    РазрешеноИспользоватьВДругихФункциях: "Нет"
    UIDФункцияСистемы: "fef4d3b0-38de-11ed-be78-000c29b8212d"
    UIDРазделПроекта: "f1acf14f-38de-11ed-be78-000c29b8212d"
    UIDОтветственный: "e7203090-38db-11ed-be78-000c29b8212d"
    Публикуется: "Нет"
    ПрофильПользователя: ""
    УровеньОтчета1: "Документ Заявка"
    УровеньОтчета2: "Документ \"Заявка\""
    ОписаниеСценария: ""

ПараметрыСценария:

ТегиСценария:

ВложенныеСценарии:

ВызывающиеСценарии:

