ТипФайла: "Сценарий"
ДанныеСценария:
    UID: "c9ee1c01-4941-11ed-be86-000c29b8212d"
    Имя: "Изменение справочника \"КабинетыИОборудование\""
    Код: "000000064"
    Проект: "БИТ:УМЦ"
    ПроектUID: "82a1df0f-598a-4887-b4a5-bc1f2fd0e030"
    ФункцияСистемы: "Основной функционал"
    РазрешеноИспользоватьВДругихФункциях: "Нет"
    UIDФункцияСистемы: "fef4d3b0-38de-11ed-be78-000c29b8212d"
    UIDРазделПроекта: "a88c3c91-4540-11ed-be85-000c29b8212d"
    UIDОтветственный: "e7203090-38db-11ed-be78-000c29b8212d"
    Публикуется: "Нет"
    ПрофильПользователя: ""
    УровеньОтчета1: "Справочник КабинетыИОборудование"
    УровеньОтчета2: "Справочник \"КабинетыИОборудование\""
    ОписаниеСценария: ""

ПараметрыСценария:
    - ПараметрыСценария1:
        НомерСтроки: "1"
        Имя: "НаименованиеКабинетаИОборудования"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария2:
        НомерСтроки: "2"
        Имя: "ыыы"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария3:
        НомерСтроки: "3"
        Имя: "ОсновнаяУслуга"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария4:
        НомерСтроки: "4"
        Имя: "Специализация"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария5:
        НомерСтроки: "5"
        Имя: "ыы"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария6:
        НомерСтроки: "6"
        Имя: "ВидКабинетаИОборудования"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"

    - ПараметрыСценария7:
        НомерСтроки: "7"
        Имя: "Подразделение"
        Значение: ""
        ТипПараметра: "Строка"
        ИсходящийПараметр: "Нет"


ТегиСценария:

ВложенныеСценарии:

ВызывающиеСценарии:

