ТипФайла: "Сценарий"
ДанныеСценария:
    UID: "11aabd27-40aa-11ed-be85-000c29b8212d"
    Имя: "Установить фото"
    Код: "000000030"
    Проект: "БИТ:УМЦ"
    ПроектUID: "82a1df0f-598a-4887-b4a5-bc1f2fd0e030"
    ФункцияСистемы: "Основной функционал"
    РазрешеноИспользоватьВДругихФункциях: "Нет"
    UIDФункцияСистемы: "fef4d3b0-38de-11ed-be78-000c29b8212d"
    UIDРазделПроекта: "2552c356-409f-11ed-be85-000c29b8212d"
    UIDОтветственный: "e7203090-38db-11ed-be78-000c29b8212d"
    Публикуется: "Нет"
    ПрофильПользователя: ""
    УровеньОтчета1: "Справочник Клиенты"
    УровеньОтчета2: "Справочник Клиенты"
    ОписаниеСценария: ""

ПараметрыСценария:

ТегиСценария:

ВложенныеСценарии:

ВызывающиеСценарии:

